// GENERATED by scripts/build-wasm.mjs -- do not edit.
// BUILD_ID is the offline service worker's cache key: it changes whenever ANY
// file in SHELL changes, because sw.js only repopulates its cache when this
// file changes. SHELL is every file sw.js must cache to run without a network.
// ALGORITHM_VERSION identifies the source revision that produced a trial's
// params (spec 3.2) and tracks the wasm alone, NOT the shell.
export const BUILD_ID = 'c40de68bd3a4';
export const ALGORITHM_VERSION = '0.1.0+5c2ffc9c05a8.acf3447a3bb9';
export const SHELL = [
  './',
  './index.html',
  './manifest.json',
  './src/app.css',
  './src/app.js',
  './src/capture.js',
  './src/db.js',
  './src/export.js',
  './src/install-gate.js',
  './src/session-store.js',
  './src/worker.js',
  './src/build-id.js',
  './src/wasm/mobile_imu_core.js',
  './src/wasm/mobile_imu_core_bg.wasm',
];
