// GENERATED by scripts/build-wasm.mjs -- do not edit.
// BUILD_ID is the offline service worker's cache key: it changes whenever ANY
// file in SHELL changes, because sw.js only repopulates its cache when this
// file changes. SHELL is every file sw.js must cache to run without a network.
// ALGORITHM_VERSION identifies the source revision that produced a trial's
// params (spec 3.2) and tracks the wasm alone, NOT the shell.
export const BUILD_ID = 'db967a2ed990';
export const ALGORITHM_VERSION = '0.1.0+ea9501787cde.7ae3c0ddf519';
export const SHELL = [
  './',
  './index.html',
  './manifest.json',
  './src/app.css',
  './src/app.js',
  './src/capture.js',
  './src/db.js',
  './src/export.js',
  './src/install-gate.js',
  './src/mas-csv.js',
  './src/mas-store.js',
  './src/router.js',
  './src/session-store.js',
  './src/trend-charts.js',
  './src/trend-import.js',
  './src/views/capture.js',
  './src/views/home.js',
  './src/views/mas.js',
  './src/views/session.js',
  './src/views/trends.js',
  './src/views/trials.js',
  './src/worker.js',
  './src/build-id.js',
  './src/wasm/mobile_imu_core.js',
  './src/wasm/mobile_imu_core_bg.wasm',
];
