import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { computeShell } from '../scripts/shell-list.mjs';
import { SHELL } from '../src/build-id.js';

// sw.js's fetch handler is cache-first with network fallback, so a SHELL
// that has drifted from the filesystem looks perfectly fine online -- the
// browser just fetches whatever SHELL forgot to list. It only breaks on a
// fully offline load, which nothing else in this suite or CI exercises.
// SHELL is only regenerated by `npm run build:wasm`, whose primary job is
// the wasm rebuild; a JS-only module (install-gate.js, db.js,
// session-store.js, export.js, ...) can be added without anyone having a
// reason to run it. These tests make that omission fail loudly instead.

const webappRoot = fileURLToPath(new URL('../', import.meta.url));
const srcDir = path.join(webappRoot, 'src');

test('SHELL in build-id.js matches a fresh scan of webapp/src/ (catches a forgotten rebuild)', () => {
  // computeShell is the exact function build-wasm.mjs calls to produce
  // SHELL -- imported, not reimplemented, so this test and the generator
  // cannot drift apart. Compared with deepEqual (order matters, since
  // computeShell sorts) rather than a set, so an ordering regression that
  // would rewrite SHELL on every unrelated build is also caught.
  const fresh = computeShell(srcDir);
  assert.deepEqual(
    SHELL,
    fresh,
    'src/build-id.js is stale -- run `npm run build:wasm` to regenerate SHELL',
  );
});

test('every SHELL entry exists on disk', () => {
  // The other half of the same property: cache.addAll() in sw.js's install
  // handler rejects as a unit if a single entry 404s, which fails the whole
  // install silently and leaves the app broken offline.
  const missing = SHELL.filter((entry) => entry !== './' && !existsSync(path.join(webappRoot, entry)));
  assert.deepEqual(missing, []);
});
