// Regenerates only the shell half of webapp/src/build-id.js (BUILD_ID and SHELL).
// Run via `npm run build:shell` from webapp/.
//
// Why this exists: build-wasm.mjs regenerates the entire build-id.js file only
// as a side effect of a Rust build, but any change to a src/*.js or src/*.css
// file invalidates SHELL and BUILD_ID without touching the wasm. sw-shell.test.js
// requires SHELL and BUILD_ID be current, so a pure-JS change would fail that
// test after you edit a file but before you run the heavy `build:wasm` rebuild.
// This script updates only the shell half, preserving ALGORITHM_VERSION, so
// the test passes immediately after a source edit and you can iterate without
// waiting for a cargo build.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { computeShell, computeBuildId } from './shell-list.mjs';

const repoRoot = new URL('../../', import.meta.url);
const srcDir = fileURLToPath(new URL('webapp/src', repoRoot));
const webappRoot = fileURLToPath(new URL('webapp/', repoRoot));
const buildIdOut = fileURLToPath(new URL('webapp/src/build-id.js', repoRoot));

function die(message) {
  console.error(`\nbuild:shell failed\n\n${message}\n`);
  process.exit(1);
}

// Read the current build-id.js to preserve ALGORITHM_VERSION
let currentContent;
try {
  currentContent = readFileSync(buildIdOut, 'utf8');
} catch {
  die(`could not read ${buildIdOut} -- run \`npm run build:wasm\` first to create it`);
}

// Extract ALGORITHM_VERSION from the current file
const algorithmVersionMatch = currentContent.match(/export const ALGORITHM_VERSION = '([^']+)'/);
if (!algorithmVersionMatch) {
  die(`could not find ALGORITHM_VERSION in ${buildIdOut} -- file may be corrupted`);
}
const algorithmVersion = algorithmVersionMatch[1];

// Compute the fresh shell and build id
const shell = computeShell(srcDir);
const buildId = computeBuildId(webappRoot, shell);

// Write in byte-identical format to build-wasm.mjs
writeFileSync(
  buildIdOut,
  `// GENERATED by scripts/build-wasm.mjs -- do not edit.\n` +
    `// BUILD_ID is the offline service worker's cache key: it changes whenever ANY\n` +
    `// file in SHELL changes, because sw.js only repopulates its cache when this\n` +
    `// file changes. SHELL is every file sw.js must cache to run without a network.\n` +
    `// ALGORITHM_VERSION identifies the source revision that produced a trial's\n` +
    `// params (spec 3.2) and tracks the wasm alone, NOT the shell.\n` +
    `export const BUILD_ID = '${buildId}';\n` +
    `export const ALGORITHM_VERSION = '${algorithmVersion}';\n` +
    `export const SHELL = [\n${shell.map((f) => `  '${f}',`).join('\n')}\n];\n`,
);
console.log(`build id ${buildId}`);
console.log(`algorithm version ${algorithmVersion}`);
console.log(`shell: ${shell.length} files`);
