//! Causal knee-flexion-axis estimator — a direct port of `imu_flex_axis.py`'s
//! `FlexAxisEstimator` (and its batch companion `principal_axis`).
//!
//! # What it is for
//!
//! A single IMU's rotation is projected onto a scalar swing angle as
//! `swing = |theta * dot(u, flex_axis)|`, so the reported amplitude is scaled
//! by the cosine of however far `flex_axis` is misaligned. The pipeline used
//! to capture that axis from the *first* raw gyro sample to cross the capture
//! threshold — the worst available moment, dominated by the release transient
//! rather than the swing. On Participant_19 that single-sample axis landed
//! 58–86° off the swing's true principal axis on all 8 trials, and the
//! pipeline duly returned 25–67% of the true excursion.
//!
//! This estimator instead accumulates the second-moment matrix of the raw gyro
//! vectors while the segment is moving and commits its dominant eigenvector.
//!
//! # Why online, not batch
//!
//! The live server sees one sample at a time and cannot look ahead, so this is
//! deliberately an online algorithm: it accumulates, exposes a provisional
//! axis immediately (so there is never a window with no axis at all), and
//! commits a refined estimate after [`MIN_COMMIT_SAMPLES`] qualifying samples.
//!
//! The vectors are **not** mean-centred: a rotation axis is a direction the
//! gyro vector lies *along* (in both signs across an oscillation), so the raw
//! second moment is the correct quantity, not the covariance about the mean.
//!
//! # Fidelity notes
//!
//! The Python obtains the dominant eigenvector from `numpy.linalg.eigh`
//! (LAPACK). This crate is dependency-free by design (it cross-compiles to
//! iOS/Android via UniFFI), so [`dominant_eigenvector_sym3`] derives it by
//! hand: closed-form symmetric-3×3 eigenvalues, a spectral-projector seed,
//! then power iteration to polish. Agreement with LAPACK is pinned against
//! golden fixtures generated by running the Python
//! (`tests/fixtures/gen_flex_axis_fixtures.py`).
//!
//! Where an eigenvalue is *degenerate* (λ₁ == λ₂) the dominant eigenvector is
//! not unique and neither LAPACK nor this port has a defined answer; that is a
//! property of the problem, not of the port. Real gyro scatter matrices from a
//! swing have a strongly separated λ₁, which is the regime this is used in.

use crate::ahrs::Vec3;

/// Minimum |ω| (rad/s) for a sample to count as deliberate motion rather than
/// noise or handling. Mirrors `_FLEX_CAPTURE_THRESHOLD` at both Python call
/// sites; passed in explicitly so neither can silently drift from the other.
pub const DEFAULT_THRESHOLD: f64 = 1.0;

/// Qualifying samples to accumulate before committing the axis. At the ~100 Hz
/// the phone logs gyro this is ~0.25 s of swing — long enough for the dominant
/// direction to dominate the release transient, short enough that the axis is
/// settled well before peak flexion (the part of the curve the amplitude
/// actually depends on).
pub const MIN_COMMIT_SAMPLES: usize = 25;

/// Guard on the horizontal-plane levelling: if the committed axis is more than
/// this far from horizontal (cosine against gravity), the setup is not the
/// geometry the correction assumes (reclined participant, abducted leg, phone
/// mounted oddly) and the unconstrained axis is kept instead.
/// `0.5` => 30° off horizontal.
pub const MAX_GRAVITY_TILT_COS: f64 = 0.5;

/// Online principal-axis estimator. Feed it raw gyro vectors via
/// [`FlexAxisEstimator::update`]; read [`FlexAxisEstimator::axis`] for the
/// current best estimate (`None` until the first above-threshold sample) and
/// [`FlexAxisEstimator::committed`] for whether it has settled.
#[derive(Debug, Clone)]
pub struct FlexAxisEstimator {
    threshold: f64,
    min_samples: usize,
    /// Second-moment (scatter) matrix Σ v vᵀ over qualifying raw gyro vectors.
    m: [[f64; 3]; 3],
    n: usize,
    axis: Option<Vec3>,
    committed: bool,
    first: Option<Vec3>,
    gravity: Option<Vec3>,
    leveled: bool,
}

impl Default for FlexAxisEstimator {
    fn default() -> Self {
        Self::new(DEFAULT_THRESHOLD, MIN_COMMIT_SAMPLES)
    }
}

impl FlexAxisEstimator {
    /// `threshold` is |ω| in rad/s; `min_samples` is the qualifying-sample
    /// count at which the axis commits.
    ///
    /// The Python takes `min_samples: int` and would commit on the first
    /// qualifying sample for any value ≤ 1 (the check is `n >= min_samples`
    /// *after* the increment). `usize` cannot express the negative case, but
    /// `0` and `1` behave identically to the Python's, so the reachable
    /// behaviour is unchanged.
    pub fn new(threshold: f64, min_samples: usize) -> Self {
        Self {
            threshold,
            min_samples,
            m: [[0.0; 3]; 3],
            n: 0,
            axis: None,
            committed: false,
            first: None,
            gravity: None,
            leveled: false,
        }
    }

    /// Current best estimate: `None` until the first above-threshold sample,
    /// then the provisional single-sample axis, then the committed one.
    pub fn axis(&self) -> Option<Vec3> {
        self.axis
    }

    /// Whether the axis has settled. Once true, `update` is a no-op.
    pub fn committed(&self) -> bool {
        self.committed
    }

    /// Qualifying (above-threshold, finite) samples accumulated so far.
    pub fn n_samples(&self) -> usize {
        self.n
    }

    /// True if the committed axis was projected onto the horizontal plane.
    pub fn leveled(&self) -> bool {
        self.leveled
    }

    /// Feed one raw gyro vector, optionally with the sensor-frame gravity
    /// direction (an accelerometer reading is fine — it is normalised here).
    ///
    /// Ignores sub-threshold samples and does nothing once committed, so
    /// callers can drive it unconditionally. Gravity is optional: without it
    /// the axis is simply not levelled.
    pub fn update(&mut self, v: Vec3, gravity: Option<Vec3>) {
        if self.committed {
            return;
        }
        if !is_finite3(v) {
            return;
        }
        let mag = norm3(v);
        if mag < self.threshold {
            return;
        }

        if self.gravity.is_none() {
            // Keep the EARLIEST reading: it sits closest to the pre-release
            // hold, where the accelerometer is measuring gravity alone rather
            // than gravity plus the swing's own linear acceleration.
            if let Some(g) = gravity {
                if is_finite3(g) {
                    let gn = norm3(g);
                    if gn > 1e-6 {
                        self.gravity = Some([g[0] / gn, g[1] / gn, g[2] / gn]);
                    }
                }
            }
        }

        let u = [v[0] / mag, v[1] / mag, v[2] / mag];
        if self.first.is_none() {
            // Provisional axis: identical to the old single-sample capture, so
            // the first fraction of a second behaves exactly as before rather
            // than having no axis at all.
            self.first = Some(u);
            self.axis = Some(u);
        }

        for i in 0..3 {
            for j in 0..3 {
                self.m[i][j] += v[i] * v[j];
            }
        }
        self.n += 1;
        if self.n >= self.min_samples {
            self.commit();
        }
    }

    fn commit(&mut self) {
        // `None` covers both of the Python's bail-outs — `LinAlgError` from
        // `eigh`, and a returned eigenvector whose norm is non-finite or
        // < 1e-12. Both keep the provisional axis and mark the estimate
        // settled so `update` stops doing work.
        let Some(mut axis) = dominant_eigenvector_sym3(&self.m) else {
            self.committed = true;
            return;
        };

        // Level it: drop the component along gravity, so the axis lies in the
        // horizontal plane the knee actually flexes about. Skipped when the
        // axis is too far from horizontal to trust the assumption.
        if let Some(g) = self.gravity {
            let along = dot3(axis, g);
            if along.abs() <= MAX_GRAVITY_TILT_COS {
                let leveled = [
                    axis[0] - along * g[0],
                    axis[1] - along * g[1],
                    axis[2] - along * g[2],
                ];
                let ln = norm3(leveled);
                // Unreachable in practice given the guard above: `axis` and `g`
                // are unit vectors, so ln == sqrt(1 - along²) >= sqrt(0.75).
                // Kept because the Python has it.
                if ln.is_finite() && ln > 1e-6 {
                    axis = [leveled[0] / ln, leveled[1] / ln, leveled[2] / ln];
                    self.leveled = true;
                }
            }
        }

        // Eigenvector sign is arbitrary; the projection takes an absolute value
        // so sign does not affect the reported angle, but pin it to the first
        // qualifying sample anyway so the stored axis is reproducible.
        if let Some(first) = self.first {
            if dot3(axis, first) < 0.0 {
                axis = [-axis[0], -axis[1], -axis[2]];
            }
        }
        self.axis = Some(axis);
        self.committed = true;
    }

    /// Return to the pre-trial state: no scatter, no axis, not committed.
    pub fn reset(&mut self) {
        self.m = [[0.0; 3]; 3];
        self.n = 0;
        self.axis = None;
        self.committed = false;
        self.first = None;
        self.gravity = None;
        self.leveled = false;
    }
}

/// Batch equivalent of [`FlexAxisEstimator`], for offline analysis and tests:
/// the dominant direction of whichever supplied gyro vectors clear
/// `threshold`.
///
/// **Sign is not defined.** The Python takes the first right singular vector
/// straight from `numpy.linalg.svd` with no sign normalisation, and LAPACK's
/// sign for a singular vector is an implementation detail, not a documented
/// convention — so it is not reproducible by any independent implementation.
/// The *direction* is well defined and is what both sides guarantee; callers
/// (and tests) must treat `axis` and `-axis` as equal. `FlexAxisEstimator`
/// does not have this problem: it pins the committed axis to the first
/// qualifying sample, which is fully reproducible.
pub fn principal_axis(vectors: &[Vec3], threshold: f64) -> Option<Vec3> {
    // Python filters non-finite rows first, bails if nothing is left, then
    // applies the magnitude threshold and requires at least 2 surviving rows.
    let finite: Vec<Vec3> = vectors.iter().copied().filter(|v| is_finite3(*v)).collect();
    if finite.is_empty() {
        return None;
    }
    let kept: Vec<Vec3> = finite
        .into_iter()
        .filter(|v| norm3(*v) >= threshold)
        .collect();
    if kept.len() < 2 {
        return None;
    }
    // The first right singular vector of A is the dominant eigenvector of AᵀA.
    let mut m = [[0.0f64; 3]; 3];
    for v in &kept {
        for i in 0..3 {
            for j in 0..3 {
                m[i][j] += v[i] * v[j];
            }
        }
    }
    dominant_eigenvector_sym3(&m)
}

/// Unit eigenvector for the **largest** (not largest-magnitude) eigenvalue of
/// a symmetric 3×3 matrix, matching `numpy.linalg.eigh` + `argmax`.
///
/// Like `eigh`'s default `UPLO='L'`, only the lower triangle of `m` is read;
/// the upper triangle is assumed to mirror it.
///
/// Returns `None` if `m` holds a non-finite entry, or if no unit-norm
/// eigenvector could be produced — the two cases where the Python keeps its
/// provisional axis instead.
///
/// Method: closed-form eigenvalues (Smith's trigonometric solution) give
/// λ₁ ≥ λ₂ ≥ λ₃. The spectral projector `(A − λ₂I)(A − λ₃I)` equals
/// `(λ₁−λ₂)(λ₁−λ₃)·P₁`, so its largest column is already along the answer and
/// makes a near-exact seed. Power iteration on the positive-semidefinite shift
/// `A − λ₃I` then polishes it — that shift is what makes "largest" rather than
/// "largest magnitude" the fixed point, so a symmetric matrix with a large
/// negative eigenvalue still agrees with `eigh` + `argmax`.
pub fn dominant_eigenvector_sym3(m: &[[f64; 3]; 3]) -> Option<Vec3> {
    let raw = [
        [m[0][0], m[1][0], m[2][0]],
        [m[1][0], m[1][1], m[2][1]],
        [m[2][0], m[2][1], m[2][2]],
    ];
    let mut scale = 0.0f64;
    for row in &raw {
        for x in row {
            if !x.is_finite() {
                return None;
            }
            scale = scale.max(x.abs());
        }
    }
    if scale == 0.0 {
        // `eigh` of the zero matrix returns the identity as its eigenvectors and
        // `argmax` over three equal eigenvalues picks index 0, i.e. column 0.
        return Some([1.0, 0.0, 0.0]);
    }
    // Eigenvectors are invariant under scaling, and working on a matrix whose
    // largest entry is 1 is what keeps the spectral projector below — whose
    // entries go as the SQUARE of the matrix's — from underflowing to zero (a
    // scatter matrix around 1e-180 does exactly that) or overflowing to
    // infinity. LAPACK balances internally for the same reason.
    let a = [
        [raw[0][0] / scale, raw[0][1] / scale, raw[0][2] / scale],
        [raw[1][0] / scale, raw[1][1] / scale, raw[1][2] / scale],
        [raw[2][0] / scale, raw[2][1] / scale, raw[2][2] / scale],
    ];

    let (_e1, e2, e3) = sym3_eigenvalues(&a);
    if !e2.is_finite() || !e3.is_finite() {
        return None;
    }

    // The spectral projector (A - λ₂I)(A - λ₃I) = (λ₁-λ₂)(λ₁-λ₃)·P₁, so its
    // largest column is already along the answer — except when λ₁ is
    // degenerate, where the projector is identically zero and the seed falls
    // back to an arbitrary basis vector.
    let mut v = projector_seed(&a, e2, e3);

    // Power iteration on A - λ₃I. That shift makes every eigenvalue
    // non-negative, so the fixed point is the LARGEST eigenvalue rather than
    // the largest in magnitude — matching `eigh` + `argmax` even when the most
    // negative eigenvalue dominates. Its real job here is a degenerate λ₁,
    // where the projector seed is useless and it walks an arbitrary starting
    // vector into the true eigenspace; inverse iteration alone does not.
    let shifted = shift_diag(&a, e3);
    for _ in 0..POWER_ITERATIONS {
        let w = mat_vec(&shifted, v);
        let n = norm3(w);
        if !n.is_finite() || n <= 0.0 {
            // A - λ₃I annihilates v: every eigenvalue is equal, so every
            // direction is a dominant eigenvector. Keep what we have.
            break;
        }
        v = [w[0] / n, w[1] / n, w[2] / n];
    }

    // Power iteration stalls exactly when λ₂/λ₁ → 1, which is also where the
    // closed-form seed is least accurate. Rayleigh-quotient inverse iteration
    // is the standard cure and converges cubically; it is guarded so it can
    // only ever improve the eigenpair, never perturb an already-exact one.
    let v = rqi_polish(&a, v);

    let n = norm3(v);
    if !n.is_finite() || n < 1e-12 {
        return None;
    }
    Some([v[0] / n, v[1] / n, v[2] / n])
}

/// Cubic convergence: from a seed already good to ~1e-5 this is done in two.
const RQI_STEPS: usize = 8;

/// Enough that a λ₂/λ₁ ratio as poor as 0.9 still converges to ~1e-14
/// (0.9^300 ≈ 2e-14), at a cost of a few microseconds — irrelevant next to the
/// 25 gyro samples that had to be collected to get here.
const POWER_ITERATIONS: usize = 300;

/// Rayleigh quotient vᵀAv for a unit v — the eigenvalue estimate v implies.
fn rayleigh(a: &[[f64; 3]; 3], v: Vec3) -> f64 {
    dot3(v, mat_vec(a, v))
}

/// ‖Av − λv‖: how far v is from being an eigenvector. Zero iff it is one.
fn residual(a: &[[f64; 3]; 3], v: Vec3, lambda: f64) -> f64 {
    let av = mat_vec(a, v);
    norm3([
        av[0] - lambda * v[0],
        av[1] - lambda * v[1],
        av[2] - lambda * v[2],
    ])
}

/// Rayleigh-quotient inverse iteration, guarded.
///
/// Note on the three guards below (the pivot test in [`solve3`], the residual
/// test, and the Rayleigh-quotient test): each is backstopped by one of the
/// others, so no input in the test suite isolates any one of them — a mutation
/// sweep finds all three individually survivable. They are kept as defence in
/// depth in a numerical kernel, not because a fixture demands them.
///
/// A step is accepted only if it *strictly reduces* the residual **and** does
/// not lower the Rayleigh quotient (beyond rounding). The first guard means an
/// already-exact eigenvector is returned untouched — residual 0 cannot be
/// beaten, so the loop exits immediately and well-conditioned inputs are
/// numerically unchanged. The second stops a near-singular solve from sliding
/// onto λ₂'s eigenvector, which would satisfy the residual guard just as well
/// but is the wrong answer for `eigh` + `argmax`.
fn rqi_polish(a: &[[f64; 3]; 3], mut v: Vec3) -> Vec3 {
    let mut rq = rayleigh(a, v);
    let mut res = residual(a, v, rq);
    if !rq.is_finite() || !res.is_finite() {
        return v;
    }
    for _ in 0..RQI_STEPS {
        let Some(w) = solve3(&shift_diag(a, rq), v) else {
            break;
        };
        let n = norm3(w);
        if !n.is_finite() || n <= 0.0 {
            break;
        }
        let cand = [w[0] / n, w[1] / n, w[2] / n];
        let cand_rq = rayleigh(a, cand);
        let cand_res = residual(a, cand, cand_rq);
        if !cand_rq.is_finite() || !cand_res.is_finite() || cand_res >= res {
            break;
        }
        let slack = 8.0 * f64::EPSILON * rq.abs().max(1.0);
        if cand_rq < rq - slack {
            break;
        }
        v = cand;
        rq = cand_rq;
        res = cand_res;
    }
    v
}

/// Solves `a x = b` by Gaussian elimination with partial pivoting. `None` when
/// the matrix is singular to working precision — which, for the deliberately
/// near-singular shifts inverse iteration uses, is a real possibility and the
/// signal to stop rather than to divide by ~0.
fn solve3(a: &[[f64; 3]; 3], b: Vec3) -> Option<Vec3> {
    let mut m = [
        [a[0][0], a[0][1], a[0][2], b[0]],
        [a[1][0], a[1][1], a[1][2], b[1]],
        [a[2][0], a[2][1], a[2][2], b[2]],
    ];
    // Scale reference for the singularity test, so it is relative not absolute.
    let scale = a
        .iter()
        .flat_map(|r| r.iter())
        .fold(0.0f64, |acc, x| acc.max(x.abs()));
    let eps = if scale > 0.0 {
        scale * 1e-15
    } else {
        return None;
    };

    for col in 0..3 {
        let mut piv = col;
        for row in (col + 1)..3 {
            if m[row][col].abs() > m[piv][col].abs() {
                piv = row;
            }
        }
        if m[piv][col].abs() <= eps {
            return None;
        }
        m.swap(col, piv);
        for row in (col + 1)..3 {
            let f = m[row][col] / m[col][col];
            for c in col..4 {
                m[row][c] -= f * m[col][c];
            }
        }
    }
    let mut x = [0.0f64; 3];
    for row in (0..3).rev() {
        let mut s = m[row][3];
        for c in (row + 1)..3 {
            s -= m[row][c] * x[c];
        }
        x[row] = s / m[row][row];
        if !x[row].is_finite() {
            return None;
        }
    }
    Some(x)
}

/// Largest-norm column of `(A − λ₂I)(A − λ₃I)`, normalised; falls back to the
/// x basis vector when that product is degenerate (λ₁ == λ₂), where the
/// dominant eigenvector is not unique anyway.
fn projector_seed(a: &[[f64; 3]; 3], e2: f64, e3: f64) -> Vec3 {
    let p = mat_mul(&shift_diag(a, e2), &shift_diag(a, e3));
    let mut best = [1.0, 0.0, 0.0];
    let mut best_n = 0.0f64;
    for j in 0..3 {
        let col = [p[0][j], p[1][j], p[2][j]];
        let n = norm3(col);
        if n.is_finite() && n > best_n {
            best_n = n;
            best = [col[0] / n, col[1] / n, col[2] / n];
        }
    }
    best
}

/// Eigenvalues of a symmetric 3×3 matrix in descending order, by Smith's
/// closed-form trigonometric solution to the characteristic cubic.
fn sym3_eigenvalues(a: &[[f64; 3]; 3]) -> (f64, f64, f64) {
    let p1 = a[0][1] * a[0][1] + a[0][2] * a[0][2] + a[1][2] * a[1][2];
    let q = (a[0][0] + a[1][1] + a[2][2]) / 3.0;
    if p1 <= 0.0 {
        // Already diagonal.
        let mut d = [a[0][0], a[1][1], a[2][2]];
        d.sort_by(|x, y| y.partial_cmp(x).unwrap_or(core::cmp::Ordering::Equal));
        return (d[0], d[1], d[2]);
    }
    let p2 = (a[0][0] - q) * (a[0][0] - q)
        + (a[1][1] - q) * (a[1][1] - q)
        + (a[2][2] - q) * (a[2][2] - q)
        + 2.0 * p1;
    let p = (p2 / 6.0).sqrt();
    if !(p > 0.0) {
        return (q, q, q);
    }
    let b = shift_diag(a, q);
    let b = [
        [b[0][0] / p, b[0][1] / p, b[0][2] / p],
        [b[1][0] / p, b[1][1] / p, b[1][2] / p],
        [b[2][0] / p, b[2][1] / p, b[2][2] / p],
    ];
    let r = det3(&b) / 2.0;
    // r must land in [-1, 1]; rounding can push it just outside.
    let phi = if r <= -1.0 {
        core::f64::consts::PI / 3.0
    } else if r >= 1.0 {
        0.0
    } else {
        r.acos() / 3.0
    };
    let e1 = q + 2.0 * p * phi.cos();
    let e3 = q + 2.0 * p * (phi + 2.0 * core::f64::consts::PI / 3.0).cos();
    // Trace is exact-ish and cheaper than a third cosine.
    let e2 = 3.0 * q - e1 - e3;
    (e1, e2, e3)
}

fn shift_diag(a: &[[f64; 3]; 3], s: f64) -> [[f64; 3]; 3] {
    [
        [a[0][0] - s, a[0][1], a[0][2]],
        [a[1][0], a[1][1] - s, a[1][2]],
        [a[2][0], a[2][1], a[2][2] - s],
    ]
}

fn mat_mul(a: &[[f64; 3]; 3], b: &[[f64; 3]; 3]) -> [[f64; 3]; 3] {
    let mut out = [[0.0f64; 3]; 3];
    for (i, row) in out.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            *cell = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
        }
    }
    out
}

fn mat_vec(a: &[[f64; 3]; 3], v: Vec3) -> Vec3 {
    [
        a[0][0] * v[0] + a[0][1] * v[1] + a[0][2] * v[2],
        a[1][0] * v[0] + a[1][1] * v[1] + a[1][2] * v[2],
        a[2][0] * v[0] + a[2][1] * v[1] + a[2][2] * v[2],
    ]
}

fn det3(a: &[[f64; 3]; 3]) -> f64 {
    a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
        - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
        + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0])
}

fn dot3(a: Vec3, b: Vec3) -> f64 {
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}

/// Deliberately the naive `sqrt(x·x)`, because that is exactly what
/// `numpy.linalg.norm` does for a 1-D array and this is used on every path the
/// Python also takes (`update`'s magnitude gate, the gravity magnitude check,
/// `principal_axis`'s row filter). Matching it to the ulp is the point. Real
/// gyro and accelerometer magnitudes are nowhere near the ~1e-162 where
/// squaring first would start to underflow, and the eigen solver — the one
/// place a vector's scale is unbounded — normalises its matrix first.
fn norm3(v: Vec3) -> f64 {
    (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt()
}


fn is_finite3(v: Vec3) -> bool {
    v[0].is_finite() && v[1].is_finite() && v[2].is_finite()
}

/// How much of the swing happened OUT of the flexion plane.
///
/// A Wartenberg pendulum test assumes the shank swings in one plane. It often
/// does not: the limb rolls during the swing, or the clinician releases with a
/// sideways nudge. That contaminates every scored parameter, because the swing
/// angle is the gyro projected onto a single axis and whatever rotation
/// happened off that axis is simply discarded.
///
/// READ THIS BEFORE INTERPRETING THE NUMBER. What it detects is rotation whose
/// AXIS MOVES during the trial, not a swing about the wrong axis. A limb
/// swinging cleanly about a tilted axis -- a phone strapped on rotated, a
/// participant seated at an angle -- is still perfectly planar and correctly
/// reads 0.0 against the axis the estimator committed. A misaligned sensor is
/// a real problem and this does not find it. This finds wobble.
///
/// This is CAPTURE QUALITY, not a clinical finding. It answers "was this trial
/// clean" -- did the limb swing in one plane -- not anything about the patient.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LateralMotion {
    /// Perpendicular share of the total angular rate: 0.0 is perfectly
    /// planar, 1.0 is entirely off-axis.
    pub fraction: f64,
    /// The largest single perpendicular component, in deg/s.
    pub peak_deg_s: f64,
}

/// `imu_flex_axis.lateral_motion`.
///
/// Returns `None` when there is nothing to measure -- no axis was committed,
/// or no sample cleared `threshold`. `None` means "not measured", which is NOT
/// the same as `Some(0.0)` ("measured, and perfectly planar"), and a caller
/// must not collapse the two.
///
/// The fraction is magnitude-weighted -- summed perpendicular magnitudes over
/// summed totals -- rather than the mean of each sample's own ratio. A plain
/// mean is dominated by near-stationary samples, where the ratio is unstable
/// and physically meaningless: at rest the gyro reads noise whose direction is
/// uniformly random, so every resting sample contributes a ratio near 1.0 and
/// drags the answer toward "all lateral" however cleanly the leg swung.
pub fn lateral_motion(vectors: &[Vec3], axis: Option<Vec3>, threshold: f64) -> Option<LateralMotion> {
    let a = axis?;
    if !a.iter().all(|v| v.is_finite()) {
        return None;
    }
    let n_a = norm3(a);
    if n_a <= 1e-12 {
        return None;
    }
    let a = [a[0] / n_a, a[1] / n_a, a[2] / n_a];

    let mut perp_sum = 0.0;
    let mut total_sum = 0.0;
    let mut peak = 0.0_f64;
    let mut used = 0usize;

    for &v in vectors {
        if !v.iter().all(|x| x.is_finite()) {
            continue;
        }
        let mag = norm3(v);
        if mag < threshold {
            continue;
        }
        let along = dot3(v, a);
        let perp = [
            v[0] - along * a[0],
            v[1] - along * a[1],
            v[2] - along * a[2],
        ];
        let pm = norm3(perp);
        perp_sum += pm;
        total_sum += mag;
        peak = peak.max(pm);
        used += 1;
    }

    if used == 0 || total_sum <= 1e-12 {
        return None;
    }
    Some(LateralMotion {
        fraction: perp_sum / total_sum,
        peak_deg_s: peak.to_degrees(),
    })
}
