// Offline shell. The cache name carries the build id, so a new wasm produces
// a new cache and the old one is deleted on activate. Without that, a phone
// could keep serving a cached wasm after the Rust changed -- running maths
// nothing verified, with no way to see it from the outside.
//
// BUILD_ID and SHELL are both generated by scripts/build-wasm.mjs, not
// hand-maintained here. SHELL in particular must never be a hard-coded list:
// cache.addAll() rejects as a unit if any single entry 404s, so a stale
// list (e.g. naming a file a later feature hasn't added yet) would fail the
// whole install silently -- the app keeps working online while being
// broken offline, which is the hardest version of this bug to notice.
import { BUILD_ID, SHELL } from './src/build-id.js';

const CACHE = `pendulastic-${BUILD_ID}`;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)));
});

self.addEventListener('activate', (e) => {
  // Delete every cache that is not this build's. This is what makes a rebuild
  // actually reach the device rather than sitting behind a stale entry.
  e.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  // Never cache the dev upload route -- it is a POST to the host and must
  // always go to the network.
  if (e.request.method !== 'GET' || url.pathname === '/upload') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request)),
  );
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});
