// Offline shell. The cache name carries the build id, so any change to any
// shell file produces a new cache and the old one is deleted on activate.
// Without that, a phone could keep serving a cached wasm after the Rust
// changed -- running maths nothing verified, with no way to see it from the
// outside.
//
// "any shell file", not "the wasm": BUILD_ID used to hash the wasm alone,
// which made this comment true of the maths and false of everything else.
// `install` below is the ONLY thing that ever populates the cache, and it
// fires only when this worker's module graph changes -- i.e. when
// build-id.js changes. So with a wasm-only key, editing app.js or app.css
// changed nothing the browser could notice, and the cache-first `fetch`
// handler below (no revalidation, by design) went on serving an installed
// phone the old app.js indefinitely. See computeBuildId in
// scripts/shell-list.mjs.
//
// BUILD_ID and SHELL are both generated by scripts/build-wasm.mjs, not
// hand-maintained here. SHELL in particular must never be a hard-coded list:
// cache.addAll() rejects as a unit if any single entry 404s, so a stale
// list (e.g. naming a file a later feature hasn't added yet) would fail the
// whole install silently -- the app keeps working online while being
// broken offline, which is the hardest version of this bug to notice.
import { BUILD_ID, SHELL } from './src/build-id.js';

const CACHE = `pendulastic-${BUILD_ID}`;

self.addEventListener('install', (e) => {
  // { cache: 'reload' } forces each of these fetches past the browser's
  // ordinary HTTP cache. Plain addAll(SHELL) fetches through it, which is
  // invisible on dev_server.py (it sends `no-store`) but not on a real static
  // host: a long max-age there lets the service worker populate ITS cache --
  // the one BUILD_ID is supposed to key -- from stale HTTP-cached responses,
  // defeating the whole build-keyed-cache design without ever touching
  // BUILD_ID or SHELL.
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(SHELL.map((u) => new Request(u, { cache: 'reload' })))),
  );
});

self.addEventListener('activate', (e) => {
  // Delete every *pendulastic-* cache that is not this build's. This is what
  // makes a rebuild actually reach the device rather than sitting behind a
  // stale entry. Scoped to our own prefix rather than every cache in the
  // origin, so this stays harmless if something else ever uses the Cache API
  // here.
  e.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names.filter((n) => n.startsWith('pendulastic-') && n !== CACHE).map((n) => caches.delete(n)),
      ),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  // Never cache the dev upload route -- it is a POST to the host and must
  // always go to the network.
  if (e.request.method !== 'GET' || url.pathname === '/upload') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request)),
  );
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});
